/*
 * @Copyright 2018-2025 HardBackNutter
 * @License GNU General Public License
 *
 * This file is part of NeverTooManyBooks.
 *
 * NeverTooManyBooks is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NeverTooManyBooks is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NeverTooManyBooks. If not, see <http://www.gnu.org/licenses/>.
 */

plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.android.kotlin apply false
    alias libs.plugins.mannodermaus.junit5 apply false
}

tasks.register("clean", Delete) {
    delete(rootProject.layout.buildDirectory)
}

ext {
    applicationId = "com.hardbacknutter.nevertoomanybooks"
    applicationVersionCode = 92
    applicationVersionName = "7.0.1"

    // see NOTES.txt in the app module
    toolChain = 17
    minSdkVersion = 26
    targetSdkVersion = 35
    compileSdkVersion = 35
}
