#!/bin/sh
#
# Copy this into .git/hooks/
# it's not functional in the project root !
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

# make sure table types are Temporary (i.e. not Standard)
function checkTempTableUsage {

  grep  -e "^[^/].*TableTypes.Standard" $1
  if [ $? == 0 ]; then
    echo "$1 contains TableTypes.Standard, aborting"
    exit 1
  fi
}
# Main src dir.
SRC="app/src/main"


PR="${SRC}/java/com/hardbacknutter/nevertomanybooks"
checkTempTableUsage "${PR}/database/DBDefinitions.java"

MF="AndroidManifest.xml"

echo "Cleaning ${SRC}/${MF}"
if [ ! -f ${SRC}/${MF} ]; then
  echo "Manifest File not found!"
  exit 1
fi

# backup to the 'outside' with developer keys
cp ${SRC}/${MF} ../${MF}_`date +%Y-%m-%d_%H-%M-%S`.txt
# remove developer keys (all manifest meta-data values really)
sed -i -e 's/android:value=".*"/android:value=""/g' ${SRC}/${MF}


