#!/bin/sh
#
# Copy this into .git/hooks/
# it's not functional in the project root !
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#


# make sure table types are Temporary (i.e. not Standard)
function checkTempTableUsage {
  grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java
  if [ $? == 0 ]; then
    echo "src/com/eleybourn/bookcatalogue/booklist/BooklistBuilder.java contains TableTypes.Standard, aborting"
    exit 1
  fi

  grep -e TableTypes.Standard src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java
  if [ $? == 0 ]; then
    echo "src/com/eleybourn/bookcatalogue/booklist/FlattenedBooklist.java contains TableTypes.Standard, aborting"
    exit 1
  fi
}

MF=AndroidManifest.xml
echo "Cleaning $MF"
if [ ! -f $MF ]; then
  echo "Manifest File not found!"
  exit 1
fi

# backup to the 'outside' with developer keys
cp $MF ../BC-AndroidManifest_`date +%Y-%m-%d_%H-%M-%S`.xml
# remove developer keys (all manifest meta-data values really)
sed -i -e 's/android:value=".*"/android:value=""/g' $MF

