#!/bin/sh
#
# Copy this into .git/hooks/
# it's not functional in the project root !
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

# Main src dir.
SRC="app/src/main"

PR="${SRC}/java/com/hardbacknutter/nevertoomanybooks"

MF="AndroidManifest.xml"

echo "Cleaning ${SRC}/${MF}"
if [ ! -f ${SRC}/${MF} ]; then
  echo "Manifest File not found!"
  exit 1
fi

# backup to the 'outside' with developer keys
cp ${SRC}/${MF} ../${MF}_`date +%Y-%m-%d_%H-%M-%S`.txt
# remove developer keys (all manifest meta-data values really)
sed -i -e 's/android:value=".*"/android:value=""/g' ${SRC}/${MF}


