[versions]
# Android 8.0
minSdk = "26"
# Android 16
targetSdk = "36"
compileSdk = "36"

# JDK used by Gradle
javaToolchain = "21"

androidGradlePlugin = "9.1.0"
# https://github.com/mannodermaus/android-junit-framework
mannodermausPlugin = "2.0.1"
mannodermausInstrumentation = "2.0.1"

# https://developer.android.com/jetpack/androidx/versions

androidxActivity = "1.13.0"
androidxAnnotation = "1.10.0"
androidxAppcompat = "1.7.1"
androidxCamerax = "1.6.0"
androidxCardview = "1.0.0"
androidxCollection = "1.6.0"
androidxConstraintlayoutCore = "1.1.1"
androidxConstraintlayout = "2.2.1"
androidxCoordinatorlayout = "1.3.0"
androidxCoreSplashscreen = '1.2.0'
androidxCore = "1.18.0"
androidxCustomview = "1.2.0"
androidxDocumentfile = "1.1.0"
androidxDrawerlayout = "1.2.0"
androidxExifinterface = "1.4.2"
androidxFragment = "1.8.9"
androidxInterpolator = "1.0.0"
androidxLifecycle = "2.10.0"
androidxPreference = "1.2.1"
androidxRecyclerview = "1.4.0"
androidxViewpager2 = '1.1.0'
androidxWindow = "1.5.1"

# https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
desugar = "2.1.5"

# https://github.com/material-components/material-components-android/releases
material = '1.13.0'

# jsoup HTML parser library @ https://jsoup.org/
jsoup = "1.22.1"
# jsoup uses/needs https://github.com/google/re2j
re2j = "1.8"

# https://github.com/square/okhttp
okhttpAndroid = "5.3.2"

# https://github.com/rburgst/okhttp-digest
okhttpAuthenticationDiggest = "3.1.1"

# http://commons.apache.org/proper/commons-codec/
apacheCommonsCodec = "1.21.0"
# http://commons.apache.org/proper/commons-compress/
apacheCommonsCompress = "1.28.0"

# https://github.com/zxing/zxing
zxingCore = "3.5.4"
# CameraX based scanner code from https://github.com/tfonteyn/TinyZXingWrapper
tinyzxingwrapper = "1.3.1"

# https://github.com/ACRA/acra
# https://www.acra.ch/docs/Setup/
acra = "5.13.1"

# https://junit.org/junit5/docs/current/user-guide/#overview
# Android/mannodermaus does not support junit 6
#noinspection NewerVersionAvailable
jupiter = "5.14.2"

# https://developer.android.com/jetpack/androidx/releases/test
androidxTestCore = '1.7.0'
androidxTestRunner = '1.7.0'

# An explicit dependency must be added to avoid gradle/studio/bugs?
# adding (in some unknown circumstances) two different kotlin-stdlib versions
# resulting in Duplicate class kotlin.* build problems.
kotlinxCoroutinesCore = "1.10.2"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamerax" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "androidxCamerax" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamerax" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCamerax" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidxCardview" }
androidx-collection = { group = "androidx.collection", name = "collection", version.ref = "androidxCollection" }
androidx-constraintlayout-core = { group = "androidx.constraintlayout", name = "constraintlayout-core", version.ref = "androidxConstraintlayoutCore" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "androidxCoordinatorlayout" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-customview = { group = "androidx.customview", name = "customview", version.ref = "androidxCustomview" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidxDocumentfile" }
androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "androidxDrawerlayout" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "androidxExifinterface" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-interpolator = { group = "androidx.interpolator", name = "interpolator", version.ref = "androidxInterpolator" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "androidxViewpager2" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindow" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }

acra-core = { group = "ch.acra", name = "acra-core", version.ref = "acra" }
acra-dialog = { group = "ch.acra", name = "acra-dialog", version.ref = "acra" }
apache-commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "apacheCommonsCodec" }
apache-commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "apacheCommonsCompress" }
hardbacknutter-tinyzxingwrapper = { module = "com.hardbacknutter.tinyzxingwrapper:TinyZXingWrapper", version.ref = "tinyzxingwrapper" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttpAndroid" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttpAndroid" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpAndroid" }
okhttp-authentication-diggest = { group = "io.github.rburgst", name = "okhttp-digest", version.ref = "okhttpAuthenticationDiggest" }
re2j = { group = "com.google.re2j", name = "re2j", version.ref = "re2j" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }

junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
mannodermaus-android-test-core = { group = "de.mannodermaus.junit5", name = "android-test-core", version.ref = "mannodermausInstrumentation" }
mannodermaus-android-test-runner = { group = "de.mannodermaus.junit5", name = "android-test-runner", version.ref = "mannodermausInstrumentation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
mannodermaus-junit5 = { id = "de.mannodermaus.android-junit", version.ref = "mannodermausPlugin" }
