/*
 * @Copyright 2018-2026 HardBackNutter
 * @License GNU General Public License
 *
 * This file is part of NeverTooManyBooks.
 *
 * NeverTooManyBooks is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NeverTooManyBooks is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NeverTooManyBooks. If not, see <http://www.gnu.org/licenses/>.
 */
//file:noinspection LongLine

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias libs.plugins.android.application
    alias libs.plugins.mannodermaus.junit5
}

def buildingFromCommitHash = providers.exec {
    commandLine 'git', 'rev-parse', '--short=12', 'HEAD'
}.standardOutput.asText.get().strip()

/*
    $HOME/.gradle/gradle.properties:
        NeverTooManyBooks.properties=$HOME/blah/blah/NeverTooManyBooks.properties

    $HOME/blah/blah/NeverTooManyBooks.properties:
        sign.storeFile=$HOME/blah/blah/keystore.jks
        sign.storePassword=MyStorePassword
        sign.keyAlias=MyKeyAlias
        sign.keyPassword=MyKeyPassword

 */
final def props = new Properties()
if (project.hasProperty("NeverTooManyBooks.properties")) {
    final def file = new File(project.property("NeverTooManyBooks.properties"))
    if (file.exists()) {
        props.load(new FileInputStream(file))
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.javaToolchain.get())
    }
}

/* https://kotlinlang.org/docs/gradle.html */
kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(libs.versions.javaToolchain.get()))
    }
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}

/* https://developer.android.com/reference/tools/gradle-api/8.12/com/android/build/api/dsl/package-summary */
android {
    namespace = "com.hardbacknutter.nevertoomanybooks"
    compileSdk = libs.versions.compileSdk.get().toInteger()

    // https://developer.android.com/studio/publish/app-signing
    // https://source.android.com/docs/security/features/apksigning
    signingConfigs {
        release {
            storeFile = file(props["sign.storeFile"])
            storePassword = props["sign.storePassword"]
            keyAlias = props["sign.keyAlias"]
            keyPassword = props["sign.keyPassword"]
        }
    }

    defaultConfig {
        applicationId = "com.hardbacknutter.nevertoomanybooks"
        versionCode = 123
        versionName = "7.17.0"

        minSdk = libs.versions.minSdk.get().toInteger()
        targetSdk = libs.versions.targetSdk.get().toInteger()

        // NEWTHINGS: add app language: add the string res file. No other app changes needed.
        def supportedLocales = [
                "cs", "de", "el", "en", "en_GB", "es", "fr", "gl", "hu", "it", "nl",
                "pl", "pt", "pt_BR", "ru", "sk", "sv", "ta", "tr", "vi",
                "zh_CN", "zh_TW"]
        resourceConfigurations += supportedLocales

        buildConfigField("String[]", "SUPPORTED_LOCALES",
                "new String[]{\"" + supportedLocales.join("\",\"") + "\"}")

        buildConfigField("String", "GIT_HASH", "\"${buildingFromCommitHash}\"")

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments["runnerBuilder"] =
                "de.mannodermaus.junit5.AndroidJUnit5Builder"

        // Under development; disabled for release builds in buildTypes.release
        buildConfigField("boolean", "ENABLE_BOOKFINDER", "true")
        buildConfigField("boolean", "ENABLE_LIBRARYTHING", "true")

        buildConfigField("boolean", "ENABLE_OPEN_LIBRARY_LOGIN", "true")
        buildConfigField("boolean", "ENABLE_STRIP_INFO_LOGIN", "true")
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true

            signingConfig = signingConfigs.release

            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro")

            resValue("string", "searchSuggestAuthority",
                    "${defaultConfig.applicationId}.SearchSuggestionProvider")
            resValue("string", "fileProviderAuthority",
                    "${defaultConfig.applicationId}.GenericFileProvider")

            // under development
            buildConfigField("boolean", "ENABLE_BOOKFINDER", "false")
            buildConfigField("boolean", "ENABLE_LIBRARYTHING", "false")

            buildConfigField("boolean", "ENABLE_OPEN_LIBRARY_LOGIN", "false")
            buildConfigField("boolean", "ENABLE_STRIP_INFO_LOGIN", "false")
        }
        beta {
            initWith(release)

            versionNameSuffix = "-beta"
            // applicationIdSuffix: same as release to be able to update rel->beta

            resValue("string", "searchSuggestAuthority",
                    "${defaultConfig.applicationId}.SearchSuggestionProvider.beta")
            resValue("string", "fileProviderAuthority",
                    "${defaultConfig.applicationId}.GenericFileProvider.beta")
        }
        debug {
            debuggable = true
            versionNameSuffix = "-debug"
            applicationIdSuffix = ".debug"

            resValue("string", "searchSuggestAuthority",
                    "${defaultConfig.applicationId}.SearchSuggestionProvider.debug")
            resValue("string", "fileProviderAuthority",
                    "${defaultConfig.applicationId}.GenericFileProvider.debug")
        }
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
        resValues = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11

        // https://developer.android.com/studio/releases/#4-0-0-desugar
        coreLibraryDesugaringEnabled = true
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            // Can be enabled to make Log.x work. OR, use Logger.x
            returnDefaultValues = false
        }
    }

    packagingOptions {
        resources {
            excludes += ["META-INF/LICENSE",
                         "META-INF/LICENSE.md",
                         "META-INF/LICENSE.txt",
                         "META-INF/license.txt",
                         "META-INF/LICENSE-notice.md",
                         "META-INF/NOTICE",
                         "META-INF/NOTICE.txt",
                         "META-INF/notice.txt",
                         "META-INF/ASL2.0",
                         "META-INF/DEPENDENCIES",
                         "META-INF/README.md",
                         "META-INF/CHANGES"]
        }
    }

    lint {
        // allow command line builds to complete
        abortOnError = false
    }

    // https://developer.android.com/build/dependencies#dependency-info-play
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }

    // ENHANCE: https://developer.android.com/guide/topics/resources/app-languages#auto-localeconfig
    //    androidResources {
    //        generateLocaleConfig = true
    //    }

    androidComponents {
        onVariants(selector().all(), { variant ->
            variant.outputs.each { output ->
                def name = "${rootProject.name}-${output.versionName.get()}.apk"
                output.outputFileName.set(name)
            }
        })
    }

    // This configuration specifies how an app bundle should be split
    // in terms of language, density and cpu architecture (abi).
    // The default values are true. This means a split will be generated.
    bundle {
        language {
            enableSplit = false
        }
//        density {
//            enableSplit = true
//        }
//        abi {
//            enableSplit = true
//        }
    }
}

dependencies {
    implementation project(path: ":core")
    implementation project(path: ":fastscroller")
    implementation project(path: ":zratingbar")
    implementation project(path: ":Insets")
    implementation project(path: ":LiveDataEvent")
    implementation project(path: ":Logger")
    implementation project(path: ":repacked-org-json")

    coreLibraryDesugaring(libs.google.desugar)

    implementation(libs.androidx.activity)
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.camera.camera2)
    implementation(libs.androidx.camera.core)
    implementation(libs.androidx.camera.lifecycle)
    implementation(libs.androidx.camera.view)
    implementation(libs.androidx.cardview)
    implementation(libs.androidx.collection)
    implementation(libs.androidx.constraintlayout.core)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.coordinatorlayout)
    implementation(libs.androidx.core)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.customview)
    implementation(libs.androidx.documentfile)
    implementation(libs.androidx.drawerlayout)
    implementation(libs.androidx.exifinterface)
    implementation(libs.androidx.fragment)
    implementation(libs.androidx.lifecycle.livedata)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.preference)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.viewpager2)
    implementation(libs.androidx.window)

    implementation(libs.google.material)

    implementation(libs.jsoup)
    implementation libs.re2j

    implementation(libs.okhttp)
    implementation(libs.okhttp.urlconnection)
    implementation(libs.okhttp.logging.interceptor)
    implementation(libs.okhttp.authentication.diggest)

    // Tar file import for BC backups
    implementation(libs.apache.commons.codec)
    implementation(libs.apache.commons.compress)

    // CameraX based scanner code from "TinyZXingWrapper"
    releaseImplementation(libs.hardbacknutter.tinyzxingwrapper) {
        artifact {
            classifier = "release"
            type = "aar"
        }
    }
    betaImplementation(libs.hardbacknutter.tinyzxingwrapper) {
        artifact {
            classifier = "release"
            type = "aar"
        }
    }
    debugImplementation(libs.hardbacknutter.tinyzxingwrapper) {
        artifact {
            classifier = "debug"
            type = "aar"
        }
    }

    implementation(libs.zxing.core)

    implementation(libs.acra.core)
    implementation(libs.acra.dialog)

    implementation(libs.kotlinx.coroutines.android)

    testRuntimeOnly(libs.junit.jupiter.engine)
    testImplementation(libs.junit.jupiter.api)
    testImplementation(libs.junit.jupiter.params)

    androidTestRuntimeOnly(libs.junit.jupiter.engine)
    androidTestImplementation(libs.junit.jupiter.api)
    androidTestImplementation(libs.junit.jupiter.params)

    androidTestImplementation(libs.mannodermaus.android.test.core)
    androidTestRuntimeOnly(libs.mannodermaus.android.test.runner)

    androidTestImplementation(libs.androidx.test.core) {
        exclude group: "junit", module: "junit"
    }
    androidTestImplementation(libs.androidx.test.runner) {
        exclude group: "junit", module: "junit"
    }
}
